AWSTemplateFormatVersion: '2010-09-09'
Description: This CloudFormation template can be used to create a Cross-Account Role that allows access to Couchbase Server.
Parameters:
  IAMRoleName:
    Description: Customize the name of IAM Cross Account role for Couchbase integration
    Type: String
    Default: IAM_R_COUCHBASE_SECURITY
  ParentAccountId:
    Description: Customize the name of IAM Cross Account role for Couchbase integration
    Type: String
    Default: '1234123412341234'
Resources:
  CouchbaseSecurityMember:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub 'arn:${AWS::Partition}:iam::${ParentAccountId}:role/${IAMRoleName}'
            Action:
              - sts:AssumeRole
      RoleName: IAM_R_COUCHBASE_SECURITY_XA
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
