AWSTemplateFormatVersion: '2010-09-09'
Description: This CloudFormation template can be used to create a Cross-Account Role that allows access to Couchbase Server.
Parameters:
  ParentAccountId:
    Description: Customize the name of IAM Cross Account role for Couchbase integration
    Type: String
    Default: '1234123412341234'
Resources:
  CouchbaseSecurityMember:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub 'arn:${AWS::Partition}:iam::${ParentAccountId}:role/CB-Access-${AWS::AccountId}'
            Action:
              - sts:AssumeRole
      RoleName:         
        Fn::Join:
          - "-"
          - - CB-Access
          - Ref: AWS::AccountId
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
